name: Deploy to GitHub Pages

# when it runs
on:
  push:
    branches: [ main ]

# grant write access to the repo’s contents
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate env.js in repo root
        run: |
          cat env.template.js | envsubst > env.js
        env:
          FIREBASE_API_KEY:     ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_PROJECT_ID:  ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET:    ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID:       ${{ secrets.FIREBASE_APP_ID }}

      - name: Prepare dist
        run: |
          rm -rf dist
          mkdir dist
          cp index.html   dist/
          cp env.js       dist/
          # cp -r assets/   dist/assets/   # if you have other folders

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
